# Generated by Django 4.2.11 on 2024-05-30 19:22

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Endpoint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("endpoint_slug", models.SlugField(max_length=250, unique=True)),
                ("cluster", models.CharField(max_length=250)),
                ("framework", models.CharField(max_length=250)),
                ("model", models.CharField(max_length=250)),
                ("endpoint_uuid", models.CharField(max_length=250)),
                ("function_uuid", models.CharField(max_length=250)),
            ],
        ),
    ]
