# Generated by Django 4.2.14 on 2024-08-23 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Endpoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endpoint_slug', models.SlugField(max_length=100, unique=True)),
                ('cluster', models.CharField(max_length=100)),
                ('framework', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('endpoint_uuid', models.CharField(max_length=100)),
                ('function_uuid', models.CharField(max_length=100)),
                ('api_port', models.IntegerField(default=8000)),
            ],
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=100)),
                ('endpoint_slug', models.SlugField(max_length=100, null=True)),
                ('openai_endpoint', models.CharField(max_length=100, null=True)),
                ('prompt', models.TextField(null=True)),
                ('task_uuid', models.CharField(max_length=100, null=True)),
                ('sync', models.BooleanField()),
                ('timestamp_receive', models.DateTimeField(null=True)),
                ('timestamp_submit', models.DateTimeField(null=True)),
                ('timestamp_response', models.DateTimeField(blank=True, null=True)),
                ('response_status', models.IntegerField(null=True)),
                ('result', models.TextField(null=True)),
            ],
        ),
    ]
