# Generated by Django 4.2.13 on 2024-06-11 22:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("resource_server", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Log",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("username", models.CharField(max_length=100)),
                ("cluster", models.CharField(max_length=100)),
                ("framework", models.CharField(max_length=100)),
                ("model", models.CharField(max_length=100)),
                ("prompt", models.TextField()),
                ("task_uuid", models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name="endpoint",
            name="cluster",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="endpoint",
            name="endpoint_slug",
            field=models.SlugField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name="endpoint",
            name="endpoint_uuid",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="endpoint",
            name="framework",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="endpoint",
            name="function_uuid",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="endpoint",
            name="model",
            field=models.CharField(max_length=100),
        ),
    ]
