# Generated by Django 5.1.1 on 2024-11-22 22:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("resource_server", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="endpoint",
            name="allowed_globus_groups",
            field=models.TextField(blank=True, default=""),
        ),
    ]
