# Generated by Django 5.1.4 on 2025-01-07 21:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("resource_server", "0002_endpoint_allowed_globus_groups"),
    ]

    operations = [
        migrations.CreateModel(
            name="ListEndpointsLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("username", models.CharField(max_length=100)),
                ("endpoint_slugs", models.TextField(blank=True, default="")),
                ("task_uuids", models.TextField(blank=True, default="")),
                ("timestamp_receive", models.DateTimeField(null=True)),
                ("timestamp_response", models.DateTimeField(blank=True, null=True)),
                ("response_status", models.IntegerField(null=True)),
                ("error_message", models.TextField(blank=True, default="")),
            ],
        ),
    ]
