# Generated by Django 5.1.4 on 2025-01-23 21:09

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("resource_server", "0003_listendpointslog"),
    ]

    operations = [
        migrations.CreateModel(
            name="Batch",
            fields=[
                (
                    "batch_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("username", models.CharField(max_length=100)),
                ("input_file", models.CharField(max_length=500)),
                ("output_file_path", models.CharField(blank=True, max_length=500)),
                ("cluster", models.CharField(max_length=100)),
                ("framework", models.CharField(max_length=100)),
                ("model", models.CharField(max_length=250)),
                ("globus_batch_uuid", models.CharField(max_length=100)),
                ("globus_task_uuids", models.TextField(null=True)),
                ("result", models.TextField(blank=True)),
                ("status", models.CharField(default="pending", max_length=250)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("in_progress_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("failed_at", models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
