# Generated by Django 4.2.11 on 2024-07-17 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resource_server', '0003_add_openai_endpoint_to_log'),
    ]

    operations = [
        migrations.AddField(
            model_name='endpoint',
            name='api_port',
            field=models.IntegerField(default=8000),
        ),
    ]
