# Generated by Django 4.2.14 on 2024-07-31 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resource_server', '0004_endpoint_api_port'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='log',
            name='cluster',
        ),
        migrations.RemoveField(
            model_name='log',
            name='completed',
        ),
        migrations.RemoveField(
            model_name='log',
            name='framework',
        ),
        migrations.RemoveField(
            model_name='log',
            name='model',
        ),
        migrations.AddField(
            model_name='log',
            name='endpoint_slug',
            field=models.SlugField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='log',
            name='response_status',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='log',
            name='result',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='log',
            name='timestamp_receive',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='log',
            name='timestamp_response',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='log',
            name='timestamp_submit',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='log',
            name='openai_endpoint',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='log',
            name='prompt',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='log',
            name='task_uuid',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
