# Generated by Django 4.2.14 on 2024-07-25 19:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("resource_server", "0004_endpoint_api_port"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="log",
            name="cluster",
        ),
        migrations.RemoveField(
            model_name="log",
            name="completed",
        ),
        migrations.RemoveField(
            model_name="log",
            name="framework",
        ),
        migrations.RemoveField(
            model_name="log",
            name="model",
        ),
        migrations.AddField(
            model_name="log",
            name="endpoint_slug",
            field=models.SlugField(default=None, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="log",
            name="response_status",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="log",
            name="result",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="log",
            name="timestamp_receive",
            field=models.DateTimeField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="log",
            name="timestamp_response",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="log",
            name="timestamp_submit",
            field=models.DateTimeField(default=None),
            preserve_default=False,
        ),
    ]
