# Generated by Django 5.1.4 on 2025-01-27 18:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("resource_server", "0004_batch"),
    ]

    operations = [
        migrations.AddField(
            model_name="endpoint",
            name="batch_endpoint_uuid",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AddField(
            model_name="endpoint",
            name="batch_function_uuid",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
    ]
