# Generated by Django 5.1.4 on 2025-02-25 19:23

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("resource_server", "0005_endpoint_batch_endpoint_uuid_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="batch",
            old_name="output_file_path",
            new_name="output_folder_path",
        ),
    ]
