# Generated by Django 4.2.14 on 2024-07-25 22:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("resource_server", "0005_remove_log_cluster_remove_log_completed_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="log",
            name="prompt",
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name="log",
            name="timestamp_submit",
            field=models.DateTimeField(null=True),
        ),
    ]
