# Generated by Django 5.1.4 on 2025-04-23 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resource_server', '0006_rename_output_file_path_batch_output_folder_path'),
    ]

    operations = [
        migrations.CreateModel(
            name='FederatedEndpoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=250, unique=True)),
                ('target_model_name', models.CharField(db_index=True, max_length=250, unique=True)),
                ('targets', models.JSONField(default=list)),
                ('description', models.TextField(blank=True, default='')),
            ],
        ),
    ]
