# Generated by Django 4.2.14 on 2024-07-25 22:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("resource_server", "0006_alter_log_prompt_alter_log_timestamp_submit"),
    ]

    operations = [
        migrations.AlterField(
            model_name="log",
            name="task_uuid",
            field=models.CharField(max_length=100),
        ),
    ]
