# Generated by Django 5.1.4 on 2025-05-08 00:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("resource_server", "0007_federatedendpoint"),
    ]

    operations = [
        migrations.AddField(
            model_name="batch",
            name="globus_flow_run_uuid",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="batch",
            name="globus_batch_uuid",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
