# Generated by Django 4.2.14 on 2024-07-25 22:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("resource_server", "0007_alter_log_task_uuid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="log",
            name="endpoint_slug",
            field=models.SlugField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="log",
            name="openai_endpoint",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="log",
            name="task_uuid",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
