# Generated by Django 5.2.10 on 2026-01-29 22:06

import django.db.models.deletion
import django.utils.timezone
import resource_server_async.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccessLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('timestamp_request', models.DateTimeField(db_index=True, null=True)),
                ('timestamp_response', models.DateTimeField(null=True)),
                ('api_route', models.CharField(max_length=256)),
                ('origin_ip', models.CharField(max_length=250)),
                ('status_code', models.IntegerField(db_index=True)),
                ('error', models.TextField(null=True)),
                ('authorized_groups', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='BatchLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('input_file', models.CharField(max_length=500)),
                ('output_folder_path', models.CharField(blank=True, max_length=500)),
                ('cluster', models.CharField(max_length=100)),
                ('framework', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=250)),
                ('globus_batch_uuid', models.CharField(max_length=100, null=True)),
                ('task_ids', models.TextField(null=True)),
                ('result', models.TextField(blank=True)),
                ('status', models.CharField(default='pending', max_length=250)),
                ('in_progress_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('failed_at', models.DateTimeField(blank=True, null=True)),
                ('access_log', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='batch_log', to='resource_server_async.accesslog')),
            ],
        ),
        migrations.CreateModel(
            name='Cluster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cluster_name', models.CharField(max_length=100, unique=True)),
                ('frameworks', resource_server_async.models.StrListJSONField()),
                ('openai_endpoints', resource_server_async.models.OpenAIEndpointListJSONField()),
                ('cluster_adapter', models.CharField(max_length=250)),
                ('allowed_globus_groups', resource_server_async.models.StrListJSONField(blank=True, default=list)),
                ('allowed_domains', resource_server_async.models.StrListJSONField(blank=True, default=list)),
                ('config', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Endpoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endpoint_slug', models.SlugField(max_length=100, unique=True)),
                ('cluster', models.CharField(max_length=100)),
                ('framework', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('endpoint_adapter', models.CharField(max_length=250)),
                ('allowed_globus_groups', resource_server_async.models.StrListJSONField(blank=True, default=list)),
                ('allowed_domains', resource_server_async.models.StrListJSONField(blank=True, default=list)),
                ('config', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='RequestLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cluster', models.CharField(max_length=100)),
                ('framework', models.CharField(max_length=100)),
                ('model', models.CharField(db_index=True, max_length=100)),
                ('openai_endpoint', models.CharField(max_length=100)),
                ('timestamp_compute_request', models.DateTimeField()),
                ('timestamp_compute_response', models.DateTimeField()),
                ('prompt', models.TextField(null=True)),
                ('result', models.TextField(null=True)),
                ('task_uuid', models.CharField(max_length=100, null=True)),
                ('metrics_processed', models.BooleanField(default=False)),
                ('access_log', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='request_log', to='resource_server_async.accesslog')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=100)),
                ('idp_id', models.CharField(blank=True, default='', max_length=100)),
                ('idp_name', models.CharField(max_length=100)),
                ('auth_service', models.CharField(choices=[('globus', 'Globus')], default='globus', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='BatchMetrics',
            fields=[
                ('batch', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='metrics', serialize=False, to='resource_server_async.batchlog')),
                ('cluster', models.CharField(db_index=True, max_length=100)),
                ('framework', models.CharField(db_index=True, max_length=100)),
                ('model', models.CharField(db_index=True, max_length=250)),
                ('status', models.CharField(blank=True, db_index=True, max_length=50, null=True)),
                ('total_tokens', models.BigIntegerField(null=True)),
                ('num_responses', models.BigIntegerField(null=True)),
                ('response_time_sec', models.FloatField(null=True)),
                ('throughput_tokens_per_sec', models.FloatField(null=True)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('completed_at', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RequestMetrics',
            fields=[
                ('request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='metrics', serialize=False, to='resource_server_async.requestlog')),
                ('cluster', models.CharField(max_length=100)),
                ('framework', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('status_code', models.IntegerField(null=True)),
                ('prompt_tokens', models.BigIntegerField(null=True)),
                ('completion_tokens', models.BigIntegerField(null=True)),
                ('total_tokens', models.BigIntegerField(null=True)),
                ('response_time_sec', models.FloatField(null=True)),
                ('throughput_tokens_per_sec', models.FloatField(null=True)),
                ('timestamp_compute_request', models.DateTimeField(db_index=True, null=True)),
                ('timestamp_compute_response', models.DateTimeField(null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.AddField(
            model_name='accesslog',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='access_logs', to='resource_server_async.user'),
        ),
        migrations.AddIndex(
            model_name='batchlog',
            index=models.Index(fields=['-completed_at', '-in_progress_at'], name='idx_batchlog_completion'),
        ),
        migrations.AddIndex(
            model_name='batchlog',
            index=models.Index(fields=['status'], name='idx_batchlog_status'),
        ),
        migrations.AddIndex(
            model_name='requestmetrics',
            index=models.Index(fields=['cluster', 'framework'], name='idx_rmetrics_clstr_frmwrk'),
        ),
        migrations.AddIndex(
            model_name='requestmetrics',
            index=models.Index(fields=['model'], name='idx_requestmetrics_model'),
        ),
        migrations.AddIndex(
            model_name='requestlog',
            index=models.Index(fields=['cluster', 'framework'], name='idx_rlog_clstr_frmwrk'),
        ),
        migrations.AddIndex(
            model_name='requestlog',
            index=models.Index(fields=['model'], name='idx_requestlog_model'),
        ),
        migrations.AddIndex(
            model_name='requestlog',
            index=models.Index(fields=['access_log_id', 'model'], name='idx_requestlog_access_model'),
        ),
        migrations.AddIndex(
            model_name='requestlog',
            index=models.Index(fields=['timestamp_compute_request'], name='idx_rlog_ts_compute_req'),
        ),
        migrations.AddIndex(
            model_name='accesslog',
            index=models.Index(fields=['user', 'status_code'], name='idx_accesslog_user_status'),
        ),
        migrations.AddIndex(
            model_name='accesslog',
            index=models.Index(condition=models.Q(('user_id__isnull', False), models.Q(('user_id', ''), _negated=True)), fields=['user_id'], name='idx_accesslog_user_id'),
        ),
    ]
