# Generated by Django 5.2.6 on 2025-09-16 18:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("resource_server_async", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="accesslog",
            name="authorized_groups",
            field=models.TextField(null=True),
        ),
    ]
