# Generated by Django 5.2.6 on 2025-09-17 21:35

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resource_server_async', '0002_accesslog_authorized_groups'),
    ]

    operations = [
        migrations.CreateModel(
            name='BatchMetrics',
            fields=[
                ('batch', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='metrics', serialize=False, to='resource_server_async.batchlog')),
                ('cluster', models.CharField(db_index=True, max_length=100)),
                ('framework', models.CharField(db_index=True, max_length=100)),
                ('model', models.CharField(db_index=True, max_length=250)),
                ('status', models.CharField(blank=True, db_index=True, max_length=50, null=True)),
                ('total_tokens', models.BigIntegerField(null=True)),
                ('num_responses', models.BigIntegerField(null=True)),
                ('response_time_sec', models.FloatField(null=True)),
                ('throughput_tokens_per_sec', models.FloatField(null=True)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('completed_at', models.DateTimeField(null=True)),
            ],
            options={
                'indexes': [models.Index(fields=['model'], name='resource_se_model_345302_idx'), models.Index(fields=['cluster', 'framework'], name='resource_se_cluster_c1941b_idx')],
            },
        ),
        migrations.CreateModel(
            name='RequestMetrics',
            fields=[
                ('request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='metrics', serialize=False, to='resource_server_async.requestlog')),
                ('cluster', models.CharField(db_index=True, max_length=100)),
                ('framework', models.CharField(db_index=True, max_length=100)),
                ('model', models.CharField(db_index=True, max_length=100)),
                ('status_code', models.IntegerField(db_index=True, null=True)),
                ('prompt_tokens', models.BigIntegerField(null=True)),
                ('completion_tokens', models.BigIntegerField(null=True)),
                ('total_tokens', models.BigIntegerField(null=True)),
                ('response_time_sec', models.FloatField(null=True)),
                ('throughput_tokens_per_sec', models.FloatField(null=True)),
                ('timestamp_compute_request', models.DateTimeField(db_index=True, null=True)),
                ('timestamp_compute_response', models.DateTimeField(null=True)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
            ],
            options={
                'indexes': [models.Index(fields=['cluster', 'framework'], name='resource_se_cluster_fd6b46_idx'), models.Index(fields=['model'], name='resource_se_model_d37167_idx')],
            },
        ),
    ]
