# Generated by Django 5.2.6 on 2025-09-17 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resource_server_async', '0003_batchmetrics_requestmetrics'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestlog',
            name='metrics_processed',
            field=models.BooleanField(default=False),
        ),
    ]
