# Generated by Django 5.2.6 on 2025-09-22 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resource_server_async', '0004_requestlog_metrics_processed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accesslog',
            name='status_code',
            field=models.IntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name='accesslog',
            name='timestamp_request',
            field=models.DateTimeField(db_index=True, null=True),
        ),
    ]
