# Generated by Django 5.2.6 on 2025-09-30 03:16

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resource_server_async', '0005_alter_accesslog_status_code_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='batchmetrics',
            name='resource_se_model_345302_idx',
        ),
        migrations.RemoveIndex(
            model_name='batchmetrics',
            name='resource_se_cluster_c1941b_idx',
        ),
        migrations.AlterField(
            model_name='requestlog',
            name='model',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='requestmetrics',
            name='cluster',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='requestmetrics',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='requestmetrics',
            name='framework',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='requestmetrics',
            name='model',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='requestmetrics',
            name='status_code',
            field=models.IntegerField(null=True),
        ),
        migrations.AddIndex(
            model_name='accesslog',
            index=models.Index(fields=['user', 'status_code'], name='resource_se_user_id_3bc25d_idx'),
        ),
        migrations.AddIndex(
            model_name='requestlog',
            index=models.Index(fields=['cluster', 'framework'], name='resource_se_cluster_60fe2f_idx'),
        ),
        migrations.AddIndex(
            model_name='requestlog',
            index=models.Index(fields=['model'], name='resource_se_model_f5daea_idx'),
        ),
    ]
