# Generated by Django 5.2.6 on 2025-10-01 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resource_server_async', '0006_remove_batchmetrics_resource_se_model_345302_idx_and_more'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='accesslog',
            new_name='idx_accesslog_user_status',
            old_name='resource_se_user_id_3bc25d_idx',
        ),
        migrations.RenameIndex(
            model_name='requestlog',
            new_name='idx_rlog_clstr_frmwrk',
            old_name='resource_se_cluster_60fe2f_idx',
        ),
        migrations.RenameIndex(
            model_name='requestlog',
            new_name='idx_requestlog_model',
            old_name='resource_se_model_f5daea_idx',
        ),
        migrations.RunSQL(
            sql="ALTER INDEX IF EXISTS resource_se_cluster_fd6b46_idx RENAME TO idx_rmetrics_clstr_frmwrk;",
            reverse_sql="ALTER INDEX IF EXISTS idx_rmetrics_clstr_frmwrk RENAME TO resource_se_cluster_fd6b46_idx;",
        ),
        migrations.RunSQL(
            sql="ALTER INDEX IF EXISTS resource_se_model_d37167_idx RENAME TO idx_requestmetrics_model;",
            reverse_sql="ALTER INDEX IF EXISTS idx_requestmetrics_model RENAME TO resource_se_model_d37167_idx;",
        ),
        migrations.AddIndex(
            model_name='accesslog',
            index=models.Index(condition=models.Q(('user_id__isnull', False), models.Q(('user_id', ''), _negated=True)), fields=['user_id'], name='idx_accesslog_user_id'),
        ),
        migrations.AddIndex(
            model_name='requestlog',
            index=models.Index(fields=['access_log_id', 'model'], name='idx_requestlog_access_model'),
        ),
    ]
