# Generated by Django 5.2.7 on 2025-10-13 15:17

from django.db import migrations


def rename_indexes_if_exist(apps, schema_editor):
    """Rename indexes only if they exist"""
    with schema_editor.connection.cursor() as cursor:
        # Rename resource_se_cluster_fd6b46_idx if it exists
        cursor.execute("""
            DO $$
            BEGIN
                IF EXISTS (
                    SELECT 1 FROM pg_indexes WHERE indexname = 'resource_se_cluster_fd6b46_idx'
                ) THEN
                    ALTER INDEX resource_se_cluster_fd6b46_idx RENAME TO idx_rmetrics_clstr_frmwrk;
                END IF;
            END $$;
        """)
        
        # Rename resource_se_model_d37167_idx if it exists
        cursor.execute("""
            DO $$
            BEGIN
                IF EXISTS (
                    SELECT 1 FROM pg_indexes WHERE indexname = 'resource_se_model_d37167_idx'
                ) THEN
                    ALTER INDEX resource_se_model_d37167_idx RENAME TO idx_requestmetrics_model;
                END IF;
            END $$;
        """)


def reverse_rename_indexes_if_exist(apps, schema_editor):
    """Reverse: Rename indexes back only if they exist"""
    with schema_editor.connection.cursor() as cursor:
        # Rename idx_rmetrics_clstr_frmwrk back if it exists
        cursor.execute("""
            DO $$
            BEGIN
                IF EXISTS (
                    SELECT 1 FROM pg_indexes WHERE indexname = 'idx_rmetrics_clstr_frmwrk'
                ) THEN
                    ALTER INDEX idx_rmetrics_clstr_frmwrk RENAME TO resource_se_cluster_fd6b46_idx;
                END IF;
            END $$;
        """)
        
        # Rename idx_requestmetrics_model back if it exists
        cursor.execute("""
            DO $$
            BEGIN
                IF EXISTS (
                    SELECT 1 FROM pg_indexes WHERE indexname = 'idx_requestmetrics_model'
                ) THEN
                    ALTER INDEX idx_requestmetrics_model RENAME TO resource_se_model_d37167_idx;
                END IF;
            END $$;
        """)


class Migration(migrations.Migration):

    dependencies = [
        ('resource_server_async', '0007_rename_resource_se_user_id_3bc25d_idx_idx_accesslog_user_status_and_more'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunPython(rename_indexes_if_exist, reverse_rename_indexes_if_exist),
            ],
            state_operations=[
                migrations.RenameIndex(
                    model_name='requestmetrics',
                    new_name='idx_rmetrics_clstr_frmwrk',
                    old_name='resource_se_cluster_fd6b46_idx',
                ),
                migrations.RenameIndex(
                    model_name='requestmetrics',
                    new_name='idx_requestmetrics_model',
                    old_name='resource_se_model_d37167_idx',
                ),
            ],
        ),
    ]
