# Generated by Django 5.2.7 on 2025-10-17 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resource_server_async', '0008_rename_resource_se_cluster_fd6b46_idx_idx_rmetrics_clstr_frmwrk_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batchlog',
            name='completed_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddIndex(
            model_name='batchlog',
            index=models.Index(fields=['-completed_at', '-in_progress_at'], name='idx_batchlog_completion'),
        ),
        migrations.AddIndex(
            model_name='batchlog',
            index=models.Index(fields=['status'], name='idx_batchlog_status'),
        ),
        migrations.AddIndex(
            model_name='requestlog',
            index=models.Index(fields=['timestamp_compute_request'], name='idx_rlog_ts_compute_req'),
        ),
    ]
