# Generated by Django 5.2.6 on 2025-11-18 23:16

import resource_server_async.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("resource_server_async", "0009_alter_batchlog_completed_at_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Cluster",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cluster_name", models.CharField(max_length=100, unique=True)),
                ("frameworks", resource_server_async.models.StrListJSONField()),
                (
                    "openai_endpoints",
                    resource_server_async.models.OpenAIEndpointListJSONField(),
                ),
                ("cluster_adapter", models.CharField(max_length=250)),
                (
                    "allowed_globus_groups",
                    resource_server_async.models.StrListJSONField(
                        blank=True, default=list
                    ),
                ),
                (
                    "allowed_domains",
                    resource_server_async.models.StrListJSONField(
                        blank=True, default=list
                    ),
                ),
                ("config", models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name="Endpoint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("endpoint_slug", models.SlugField(max_length=100, unique=True)),
                ("cluster", models.CharField(max_length=100)),
                ("framework", models.CharField(max_length=100)),
                ("model", models.CharField(max_length=100)),
                ("endpoint_adapter", models.CharField(max_length=250)),
                (
                    "allowed_globus_groups",
                    resource_server_async.models.StrListJSONField(
                        blank=True, default=list
                    ),
                ),
                (
                    "allowed_domains",
                    resource_server_async.models.StrListJSONField(
                        blank=True, default=list
                    ),
                ),
                ("config", models.TextField(blank=True)),
            ],
        ),
        migrations.RenameField(
            model_name="batchlog",
            old_name="globus_task_uuids",
            new_name="task_ids",
        ),
    ]
