# Generated by Django 5.2.6 on 2026-01-06 21:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("resource_server_async", "0010_cluster_endpoint_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="batchlog",
            name="globus_batch_uuid",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
