# Generated by Django 5.2.9 on 2026-04-21 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resource_server_async', '0011_alter_batchlog_globus_batch_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='endpoint',
            name='tpm_model',
            field=models.IntegerField(default=100000),
        ),
        migrations.AddField(
            model_name='endpoint',
            name='tpm_user',
            field=models.IntegerField(default=60000),
        ),
    ]
