openapi: 3.0.3
info:
  title: Inference Gateway API
  version: 0.0.1
  description: Inference Gateway
paths:
  /resource_server/polaris/{framework}/completions:
    post:
      operationId: resource_server_polaris_completions_create
      description: Public point of entry to call Globus Compute endpoints on Polaris.
      parameters:
      - in: path
        name: framework
        schema:
          type: string
        required: true
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                model:
                  type: string
                temperature:
                  type: number
                  format: float
                max_tokens:
                  type: integer
                prompt:
                  type: string
                n_probs:
                  type: integer
      tags:
      - resource_server
      security:
      - bearerAuth: []
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                  message:
                    type: string
components:
  securitySchemes:
    basicAuth:
      type: http
      scheme: basic
    cookieAuth:
      type: apiKey
      in: cookie
      name: sessionid
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
