upstream backend {
    # The internal hostname and port of the Gunicorn/Django service
    server inference-gateway:7000;
}

upstream dashboard {
    server inference-gateway:7001;
}

server {
    listen 80;
    server_name localhost; # Or your specific domain

    # Root location - proxy all other requests to the Django app
    location /resource_server/ {
        proxy_pass http://backend;
        include proxy_params;
    }

    location /dashboard/ {
        proxy_pass http://dashboard/;
        include proxy_params;
    }
}
