# Generated by Django 4.2.13 on 2024-06-20 17:46

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Batch",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("username", models.CharField(max_length=100)),
                ("endpoint", models.CharField(max_length=250)),
                ("input_file_path", models.CharField(max_length=250)),
                ("machine", models.CharField(max_length=250)),
                ("metadata", models.JSONField(default=dict)),
                ("errors", models.JSONField(default=dict)),
                ("status", models.CharField(default="pending", max_length=250)),
                ("output_file_path", models.CharField(blank=True, max_length=250)),
                ("error_file_path", models.CharField(blank=True, max_length=250)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("in_progress_at", models.DateTimeField(blank=True, null=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("finalizing_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("failed_at", models.DateTimeField(blank=True, null=True)),
                ("expired_at", models.DateTimeField(blank=True, null=True)),
                ("cancelling_at", models.DateTimeField(blank=True, null=True)),
                ("cancelled_at", models.DateTimeField(blank=True, null=True)),
                ("request_counts", models.JSONField(default=dict)),
            ],
        ),
    ]
