amqp_port: 443
display_name: sophia-qdel-endpoint
engine:
  max_retries_on_system_failure: 1
  max_workers_per_node: 1
  address:
    type: address_by_interface
    ifname: ens10f0
  provider:
    init_blocks: 1
    max_blocks: 1
    min_blocks: 0
    type: LocalProvider
  type: GlobusComputeEngine
allowed_functions:
  - d03a28f0-f4be-4f3e-ac76-d97bc5fb828a