amqp_port: 443
display_name: sophia-vllm-llama3-mistral-multi-endpoint 
engine:
  type: GlobusComputeEngine
  max_retries_on_system_failure: 2
  max_workers_per_node: 100
  job_status_kwargs:
    max_idletime: 43200
  address:
    type: address_by_interface
    ifname: ens10f0
  provider:
    type: PBSProProvider
    launcher:
      type: SimpleLauncher
    account: argonne_tpc
    select_options: ngpus=8
    scheduler_options: '#PBS -l filesystems=home:eagle'
    queue: 'single-node'
    init_blocks: 0
    max_blocks: 1
    min_blocks: 0
    nodes_per_block: 1
    walltime: 12:00:00
    worker_init: |
      bash sophia-vllm-llama3-mistral-multi-endpoint-worker-init.sh 
# Limit the functions UUID that can be execute
allowed_functions:
  - 6a411c82-6b82-4d42-9119-9b799cdc4271